name: Daily Sadhguru Content Update

on:
  schedule:
    # Runs at 6:30 AM IST (1:00 AM UTC) every day
    - cron: '0 1 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 google-api-python-client
    
    - name: Run smart updater
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        python scripts/smart_updater.py
    
    - name: Commit and push if content changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "🕉️ Daily update: $(date +'%Y-%m-%d')" && git push)
